server:
  port: 8080
#------------ spring ---------------#
spring:
  profiles:
    active: dev
  mvc:    # mvc.throw-exception-if-no-handler-found 和 resources.add-mappings设置 系统统一异常处理
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#------------ mybatis ---------------#
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1  # 状态已删除
      logic-not-delete-value: 0  #状态未删除
