spring:
  application:
    name: fast-springboot
  datasource:
    url: jdbc:mysql://localhost:3306/springbootTest?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
logging:
  config: classpath:log4j2-dev.xml